"""baseline schema, plus upgrade path for the legacy SQLite database

Revision ID: ca4a67aa2044
Revises:
Create Date: 2026-10-05

WHY ONE REVISION DOES TWO JOBS
-------------------------------
This is the first Alembic revision in the project, so it has to serve two
different starting points:

1. A **brand new PostgreSQL database** (the production case). Nothing exists
   yet, so the full current schema is created.
2. The **legacy local SQLite file** ``database/emotion_app.db``, written by
   ``db.create_all()`` before Alembic existed. It already holds real rows but is
   missing the columns and indexes added since.

``upgrade()`` inspects the database and picks the right path, so a fresh
deployment and an in-place upgrade end up on the same schema.

DESIGN CONSTRAINTS
------------------
* **Additive only on the upgrade path.** No SQLite table is rebuilt and no
  column is dropped or retyped, so upgrading cannot lose existing rows.
  Alembic's autogenerated output tried to drop and recreate unnamed foreign
  keys and to flip columns to NOT NULL; on SQLite those need a table rebuild and
  the unnamed-FK directives fail outright.
* **No invented data.** New columns get the same server-side default the model
  applies in Python, so pre-existing rows read back with a meaningful non-null
  value instead of NULL.
* **Idempotent index creation.** An index is only created when the inspector
  reports it missing.

ON DELETE CASCADE: the legacy SQLite tables predate the ``ondelete='CASCADE'``
clauses in the models, so this revision does not rebuild them to attach
database-level cascades. That is not a correctness gap: ``User.detections`` and
``User.live_sessions`` both use ``cascade='all, delete-orphan'`` with
``passive_deletes=False``, so SQLAlchemy issues the deletes. Freshly created
databases do get the database-level cascade.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ca4a67aa2044'
down_revision = None
branch_labels = None
depends_on = None


# -----------------------------------------------------------------------------
# Frozen schema definitions.
#
# Written out explicitly instead of imported from models.user and friends: a
# migration is a historical record and must keep describing the schema as it
# was at this revision even after the models move on.
# -----------------------------------------------------------------------------

# A single MetaData is shared by all four tables so that the foreign keys can
# resolve their target tables when the schema is created from scratch.
_META = sa.MetaData()

_USERS = sa.Table(
    'users',
    _META,
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('username', sa.String(80), nullable=False),
    sa.Column('email', sa.String(120), nullable=False),
    sa.Column('password_hash', sa.String(256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
)

_DETECTIONS = sa.Table(
    'detections',
    _META,
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('detection_type', sa.String(20), nullable=False),
    sa.Column('emotion', sa.String(50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(500), nullable=True),
    sa.Column('processed_image_path', sa.String(500), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(100), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(
        ['user_id'], ['users.id'], name='fk_detections_user_id', ondelete='CASCADE'
    ),
)

_LIVE_SESSIONS = sa.Table(
    'live_sessions',
    _META,
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('dominant_emotion', sa.String(50), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('session_token', sa.String(100), nullable=True),
    sa.ForeignKeyConstraint(
        ['user_id'], ['users.id'], name='fk_live_sessions_user_id', ondelete='CASCADE'
    ),
)

_USER_ACTIVITIES = sa.Table(
    'user_activities',
    _META,
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(50), nullable=False),
    sa.Column('details', sa.String(500), nullable=True),
    sa.Column('ip_address', sa.String(45), nullable=True),
    sa.Column('user_agent', sa.String(500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
        ['user_id'], ['users.id'], name='fk_user_activities_user_id', ondelete='CASCADE'
    ),
)

_TABLES = (_USERS, _DETECTIONS, _LIVE_SESSIONS, _USER_ACTIVITIES)

# Every index the models declare, as (index_name, table_name, columns, unique).
#
# username and email are declared `unique=True, index=True` in models/user.py.
# SQLAlchemy renders that combination as a single UNIQUE INDEX, not as a
# separate UNIQUE constraint plus a plain index, so they must be marked unique
# here or `flask db check` would keep reporting drift.
_INDEXES = (
    ('ix_users_username', 'users', ['username'], True),
    ('ix_users_email', 'users', ['email'], True),
    ('ix_users_role', 'users', ['role'], False),
    ('ix_users_is_active', 'users', ['is_active'], False),
    ('ix_detections_user_id', 'detections', ['user_id'], False),
    ('ix_detections_detection_type', 'detections', ['detection_type'], False),
    ('ix_detections_emotion', 'detections', ['emotion'], False),
    ('ix_detections_detected_at', 'detections', ['detected_at'], False),
    ('ix_detections_session_id', 'detections', ['session_id'], False),
    ('ix_detections_user_detected', 'detections', ['user_id', 'detected_at'], False),
    ('ix_detections_type_emotion', 'detections', ['detection_type', 'emotion'], False),
    ('ix_live_sessions_user_id', 'live_sessions', ['user_id'], False),
    ('ix_live_sessions_started_at', 'live_sessions', ['started_at'], False),
    ('ix_live_sessions_session_token', 'live_sessions', ['session_token'], False),
    ('ix_live_sessions_user_started', 'live_sessions', ['user_id', 'started_at'], False),
    ('ix_user_activities_user_id', 'user_activities', ['user_id'], False),
    ('ix_user_activities_activity_type', 'user_activities', ['activity_type'], False),
    ('ix_user_activities_created_at', 'user_activities', ['created_at'], False),
    ('ix_user_activities_user_created', 'user_activities', ['user_id', 'created_at'], False),
)

# Columns added after the legacy file was first written, as
# (table, column_name, column_object). server_default mirrors the Python-side
# model default so older rows get a real value rather than NULL.
_NEW_COLUMNS = (
    ('users', 'role', sa.Column(
        'role', sa.String(20), nullable=False, server_default=sa.text("'user'"))),
    ('users', 'is_active', sa.Column(
        'is_active', sa.Boolean(), nullable=False, server_default=sa.true())),
    ('users', 'login_count', sa.Column(
        'login_count', sa.Integer(), nullable=False, server_default=sa.text('0'))),
    ('users', 'last_login_at', sa.Column(
        'last_login_at', sa.DateTime(), nullable=True)),
    ('detections', 'processed_image_path', sa.Column(
        'processed_image_path', sa.String(500), nullable=True)),
    ('live_sessions', 'session_token', sa.Column(
        'session_token', sa.String(100), nullable=True)),
)


def _existing_columns(inspector, table_name):
    """Return the set of column names currently present on a table."""
    return {col['name'] for col in inspector.get_columns(table_name)}


def _existing_indexes(inspector, table_name):
    """Return the set of index names currently present on a table."""
    return {idx['name'] for idx in inspector.get_indexes(table_name)}


def _table_definitions():
    """Map table name -> the sa.Table definition used with batch_alter_table."""
    return {
        'users': _USERS,
        'detections': _DETECTIONS,
        'live_sessions': _LIVE_SESSIONS,
        'user_activities': _USER_ACTIVITIES,
    }


def _nullable_columns(inspector, table_name, candidates):
    """Return the subset of ``candidates`` that exist and are still nullable."""
    existing = {col['name']: col for col in inspector.get_columns(table_name)}
    return [
        name for name in candidates
        if name in existing and existing[name].get('nullable')
    ]


def _foreign_keys_lack_cascade(inspector, table_name):
    """
    True when a users foreign key is missing ON DELETE CASCADE.

    The legacy tables were created before ondelete='CASCADE' reached the models.
    """
    for fk in inspector.get_foreign_keys(table_name):
        if fk.get('referred_table') != 'users':
            continue
        if not (fk.get('options') or {}).get('ondelete'):
            return True
    return False


def _enforce_constraints(inspector):
    """
    Rebuild the legacy tables that do not yet match the models.

    SQLite cannot ALTER a constraint in place, so Alembic's batch mode recreates
    each affected table from the definition above. This is the one place the
    upgrade is not purely additive, so it is driven by inspection and only runs
    for tables that actually need it - a database that is already correct is left
    completely alone. Child tables are rebuilt before parents because SQLite
    tracks foreign key references by table name.
    """
    definitions = _table_definitions()

    # rebuild[table] = set of columns to flip to NOT NULL. A table is rebuilt when
    # it appears here at all, including when the set is empty (that is the
    # foreign-key-only case), so the key is what matters, not the set's truthiness.
    rebuild = {}

    for table_name in ('detections', 'live_sessions'):
        if _foreign_keys_lack_cascade(inspector, table_name):
            rebuild[table_name] = set()

    not_null_targets = {
        'users': ('created_at', 'updated_at'),
        'live_sessions': ('created_at',),
    }
    for table_name, candidates in not_null_targets.items():
        found = _nullable_columns(inspector, table_name, candidates)
        if found:
            rebuild.setdefault(table_name, set()).update(found)

    # A batch rebuild with no queued operations is a no-op in Alembic: it never
    # recreates the table. So when a table needs rebuilding purely for its
    # foreign key, re-assert NOT NULL on the FK column. That is idempotent and it
    # guarantees the table is actually recreated from `copy_from`, which is what
    # carries ON DELETE CASCADE.
    for columns in rebuild.values():
        if not columns:
            columns.add('user_id')

    # Children first: users is referenced by all three other tables.
    for table_name in ('user_activities', 'live_sessions', 'detections', 'users'):
        if table_name not in rebuild:
            continue
        with op.batch_alter_table(table_name, copy_from=definitions[table_name]) as batch:
            for column in sorted(rebuild[table_name]):
                batch.alter_column(
                    column,
                    existing_type=(
                        sa.Integer() if column == 'user_id' else sa.DateTime()
                    ),
                    nullable=False,
                )


def _create_everything(bind):
    """Create the full schema on an empty database."""
    # _META.create_all() emits CREATE TABLE in dependency order and resolves the
    # foreign keys, then the indexes are added.
    _META.create_all(bind)
    for name, table_name, columns, unique in _INDEXES:
        op.create_index(name, table_name, columns, unique=unique)


def _upgrade_legacy(bind, inspector):
    """
    Bring a pre-Alembic schema up to date using additive changes only.

    Every step is guarded by an existence check so a partially upgraded file can
    be run through again without error.
    """
    for table_name, column_name, column in _NEW_COLUMNS:
        if not inspector.has_table(table_name):
            continue
        if column_name in _existing_columns(inspector, table_name):
            continue
        op.add_column(table_name, column.copy())

    # Bring pre-existing constraints in line with the models BEFORE creating
    # indexes: SQLite batch mode recreates each table from `copy_from`, and index
    # definitions are not part of that, so any index created beforehand would be
    # lost with the old table.
    _enforce_constraints(inspector)

    # The rebuilds above replaced tables, so anything the inspector reported
    # earlier is stale. Re-inspect before deciding which indexes are missing.
    inspector = sa.inspect(bind)

    for name, table_name, columns, unique in _INDEXES:
        if not inspector.has_table(table_name):
            continue
        if name in _existing_indexes(inspector, table_name):
            continue
        op.create_index(name, table_name, columns, unique=unique)


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('users'):
        _upgrade_legacy(bind, inspector)
    else:
        _create_everything(bind)


def _any_rows(bind, table_names):
    """True when at least one of the given tables holds a row."""
    for name in table_names:
        result = bind.execute(
            sa.text(f'SELECT 1 FROM "{name}" LIMIT 1')
        ).fetchone()
        if result:
            return True
    return False


def downgrade():
    """
    Reverse this revision.

    Two cases, told apart by whether any table still holds rows:

    * **No rows anywhere** - the schema was created by this revision on an empty
      database, so the whole thing is removed.
    * **Rows present** - this was a pre-existing legacy database. Only the
      additive changes are reversed and the original tables and data are left in
      place.

    Column drops go through batch mode because SQLite cannot DROP COLUMN
    without recreating the table. Column drops therefore run before the index
    drops, since those recreations discard the indexes anyway.
    """
    bind = op.get_bind()
    table_names = [table.name for table in _TABLES]

    if not _any_rows(bind, table_names):
        _META.drop_all(bind)
        return

    # Legacy database: drop only what this revision added, children first so the
    # foreign keys they declare stay valid while the rebuilds happen.
    #
    # copy_from is supplied on purpose. With a bare table name Alembic reflects
    # the target shape itself, and in this schema that reflection produced a
    # mismatched column list (it reached for live_sessions.session_token while
    # rebuilding detections), which failed halfway and left an
    # _alembic_tmp_<table> table behind. Naming the intended shape explicitly
    # keeps the rebuild deterministic on both SQLite and PostgreSQL.
    definitions = _table_definitions()
    for table_name in ('detections', 'live_sessions', 'users'):
        inspector = sa.inspect(bind)
        present = [
            column_name
            for _table, column_name, _column in _NEW_COLUMNS
            if _table == table_name
            and column_name in _existing_columns(inspector, table_name)
        ]
        if not present:
            continue
        with op.batch_alter_table(
            table_name, copy_from=definitions[table_name]
        ) as batch:
            for column_name in present:
                batch.drop_column(column_name)

    inspector = sa.inspect(bind)
    for name, table_name, _columns, _unique in reversed(_INDEXES):
        if not inspector.has_table(table_name):
            continue
        if name not in _existing_indexes(inspector, table_name):
            continue
        op.drop_index(name, table_name=table_name)
